# Frontend cache control
spring:
  thymeleaf:
    cache: false
  web:
    resources:
      cache:
        cachecontrol:
          no-cache: true
  data:
    redis:
      host: localhost
      port: 6379