spring:
  thymeleaf:
    cache: false
  web:
    resources:
      cache:
        cachecontrol:
          no-cache: true
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:mysql://demo-mysql/demodb
    username: dev-user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver