# FIXME: fix these settings for production mode
spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/demodb
    username: dev-user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:database/schema.sql
      data-locations:
        - classpath:database/data.local.sql
      encoding: UTF-8