version: '3.8'

services:
  demo-frontend:
    image: node:18.18.0-slim
    container_name: demo-frontend
    volumes:
      - ../frontend:/frontend
      - ../backend/demo/src/main/resources/templates:/frontend/build/templates
      - ../backend/demo/src/main/resources/static:/frontend/build/static
      - volume_trick:/frontend/node_modules
    working_dir: /frontend
    tty: true
  demo-mysql:
    image: mysql:8.0.33
    container_name: demo-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3306:3306
  demo-redis:
    image: redis:7.2.2-alpine
    container_name: demo-redis
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
    tty: true

volumes:
  volume_trick:
  redis_data: